property(_,'p',_,'line-height','1').
property(_,'h1',_,'font-size','1.7').
property(_,'h2',_,'font-size','1.5').
property(_,'a',_,'color','black').
property(_,'a',_,'text-decoration','none').
property(_,'body',_,'font-family','arial').
property(_,'body',_,'font-size','80').
property(_,'body',_,'line-height','1.2').
property(_,'body',_,'width','100').
property(_,'body',_,'margin','0').
property(_,'body',_,'background','#eee').
property('page',_,_,'margin','20').
property('logo',_,_,'width','35').
property('logo',_,_,'margin-top','5').
property('logo',_,_,'font-family','georgia').
property('logo',_,_,'display','inline-block').
property('nav',_,_,'width','60').
property('nav',_,_,'display','inline-block').
property('nav',_,_,'text-align','right').
property('nav',_,_,'float','right').
property('content',_,_,'background','white').
property('content',_,_,'padding','20').
property('content',_,_,'clear','both').
property('footer',_,_,'margin-bottom','10').
