property('id1','tag','html').
property('id1','id','id1').
parent('id1','id2').
property('id2','tag','head').
property('id2','id','id2').
parent('id2','id3').
property('id3','tag','title').
property('id3','id','id3').
parent('id2','id4').
property('id4','tag','meta').
property('id4','name','author').
property('id4','content','your name').
property('id4','id','id4').
parent('id2','id5').
property('id5','tag','meta').
property('id5','name','description').
property('id5','content','').
property('id5','id','id5').
parent('id2','id6').
property('id6','tag','link').
property('id6','rel','stylesheet').
property('id6','href','style.css').
property('id6','type','text/css').
property('id6','id','id6').
parent('id1','id7').
property('id7','tag','body').
property('id7','id','id7').
parent('id7','page').
property('page','tag','div').
property('page','id','page').
parent('page','logo').
property('logo','tag','div').
property('logo','id','logo').
parent('logo','id8').
property('id8','tag','h1').
property('id8','id','id8').
parent('id8','logoLink').
property('logoLink','tag','a').
property('logoLink','href','/').
property('logoLink','id','logoLink').
parent('page','nav').
property('nav','tag','div').
property('nav','id','nav').
parent('nav','id9').
property('id9','tag','ul').
property('id9','id','id9').
parent('id9','id10').
property('id10','tag','li').
property('id10','id','id10').
parent('id10','id11').
property('id11','tag','a').
property('id11','href','#/home.html').
property('id11','id','id11').
parent('id9','id12').
property('id12','tag','li').
property('id12','id','id12').
parent('id12','id13').
property('id13','tag','a').
property('id13','href','#/about.html').
property('id13','id','id13').
parent('id9','id14').
property('id14','tag','li').
property('id14','id','id14').
parent('id14','id15').
property('id15','tag','a').
property('id15','href','#/contact.html').
property('id15','id','id15').
parent('page','content').
property('content','tag','div').
property('content','id','content').
parent('content','id16').
property('id16','tag','h2').
property('id16','id','id16').
parent('content','id17').
property('id17','tag','p').
property('id17','id','id17').
parent('content','id18').
property('id18','tag','p').
property('id18','id','id18').
parent('page','footer').
property('footer','tag','div').
property('footer','id','footer').
parent('footer','id19').
property('id19','tag','p').
property('id19','id','id19').
parent('id19','id20').
property('id20','tag','a').
property('id20','href','/').
property('id20','target','_blank').
property('id20','id','id20').
