property('id1','tag','html').
property('id1','id','id1').
parent('id1','id2').
property('id2','tag','head').
property('id2','id','id2').
parent('id2','id3').
property('id3','tag','title').
property('id3','id','id3').
parent('id2','id4').
property('id4','tag','link').
property('id4','rel','stylesheet').
property('id4','href','mystyle.css').
property('id4','id','id4').
parent('id1','id5').
property('id5','tag','body').
property('id5','id','id5').
parent('id5','id6').
property('id6','tag','ul').
property('id6','class','navbar').
property('id6','id','id6').
parent('id6','id7').
property('id7','tag','li').
property('id7','id','id7').
parent('id7','id8').
property('id8','tag','a').
property('id8','href','index.html').
property('id8','id','id8').
parent('id6','id9').
property('id9','tag','li').
property('id9','id','id9').
parent('id9','id10').
property('id10','tag','a').
property('id10','href','musings.html').
property('id10','id','id10').
parent('id6','id11').
property('id11','tag','li').
property('id11','id','id11').
parent('id11','id12').
property('id12','tag','a').
property('id12','href','town.html').
property('id12','id','id12').
parent('id6','id13').
property('id13','tag','li').
property('id13','id','id13').
parent('id13','id14').
property('id14','tag','a').
property('id14','href','links.html').
property('id14','id','id14').
parent('id5','id15').
property('id15','tag','h1').
property('id15','id','id15').
parent('id5','id16').
property('id16','tag','p').
property('id16','id','id16').
parent('id5','id17').
property('id17','tag','p').
property('id17','id','id17').
parent('id5','id18').
property('id18','tag','p').
property('id18','id','id18').
parent('id5','id19').
property('id19','tag','address').
property('id19','id','id19').
parent('id19','id20').
property('id20','tag','br').
property('id20','id','id20').
