property('id1','tag','html').
property('id1','lang','en').
property('id1','id','id1').
parent('id1','id2').
property('id2','tag','head').
property('id2','id','id2').
parent('id2','id3').
property('id3','tag','meta').
property('id3','charset','utf-8').
property('id3','id','id3').
parent('id2','id4').
property('id4','tag','meta').
property('id4','http-equiv','X-UA-Compatible').
property('id4','content','IE=edge').
property('id4','id','id4').
parent('id2','id5').
property('id5','tag','meta').
property('id5','name','viewport').
property('id5','content','width=device-width, initial-scale=1').
property('id5','id','id5').
parent('id2','id6').
property('id6','tag','title').
property('id6','id','id6').
parent('id2','id7').
property('id7','tag','link').
property('id7','href','css/bootstrap.min.css').
property('id7','rel','stylesheet').
property('id7','id','id7').
parent('id2','id8').
property('id8','tag','link').
property('id8','href','css/custom.css').
property('id8','rel','stylesheet').
property('id8','id','id8').
parent('id1','id9').
property('id9','tag','body').
property('id9','id','id9').
parent('id9','id10').
property('id10','tag','nav').
property('id10','class','navbar navbar-inverse navbar-fixed-top').
property('id10','role','navigation').
property('id10','id','id10').
parent('id10','id11').
property('id11','tag','div').
property('id11','class','container').
property('id11','id','id11').
parent('id11','id12').
property('id12','tag','div').
property('id12','class','navbar-header').
property('id12','id','id12').
parent('id12','id13').
property('id13','tag','button').
property('id13','type','button').
property('id13','class','navbar-toggle').
property('id13','data-toggle','collapse').
property('id13','data-target','#navbar').
property('id13','id','id13').
parent('id13','id14').
property('id14','tag','span').
property('id14','class','sr-only').
property('id14','id','id14').
parent('id13','id15').
property('id15','tag','span').
property('id15','class','icon-bar').
property('id15','id','id15').
parent('id13','id16').
property('id16','tag','span').
property('id16','class','icon-bar').
property('id16','id','id16').
parent('id13','id17').
property('id17','tag','span').
property('id17','class','icon-bar').
property('id17','id','id17').
parent('id12','id18').
property('id18','tag','a').
property('id18','class','navbar-brand').
property('id18','href','#').
property('id18','id','id18').
parent('id18','id19').
property('id19','tag','span').
property('id19','class','glyphicon glyphicon-fire').
property('id19','id','id19').
parent('id11','navbar').
property('navbar','tag','div').
property('navbar','class','collapse navbar-collapse').
property('navbar','id','navbar').
parent('navbar','id20').
property('id20','tag','ul').
property('id20','class','nav navbar-nav').
property('id20','id','id20').
parent('id20','id21').
property('id21','tag','li').
property('id21','class','active').
property('id21','id','id21').
parent('id21','id22').
property('id22','tag','a').
property('id22','href','#').
property('id22','id','id22').
parent('id20','id23').
property('id23','tag','li').
property('id23','id','id23').
parent('id23','id24').
property('id24','tag','a').
property('id24','href','#').
property('id24','id','id24').
parent('id20','id25').
property('id25','tag','li').
property('id25','id','id25').
parent('id25','id26').
property('id26','tag','a').
property('id26','href','#').
property('id26','id','id26').
parent('id20','id27').
property('id27','tag','li').
property('id27','class','dropdown').
property('id27','id','id27').
parent('id27','id28').
property('id28','tag','a').
property('id28','href','#').
property('id28','class','dropdown-toggle').
property('id28','data-toggle','dropdown').
property('id28','role','button').
property('id28','aria-haspopup','true').
property('id28','aria-expanded','false').
property('id28','id','id28').
parent('id28','id29').
property('id29','tag','span').
property('id29','class','caret').
property('id29','id','id29').
parent('id27','id30').
property('id30','tag','ul').
property('id30','class','dropdown-menu').
property('id30','aria-labelledby','about-us').
property('id30','id','id30').
parent('id30','id31').
property('id31','tag','li').
property('id31','id','id31').
parent('id31','id32').
property('id32','tag','a').
property('id32','href','#').
property('id32','id','id32').
parent('id30','id33').
property('id33','tag','li').
property('id33','id','id33').
parent('id33','id34').
property('id34','tag','a').
property('id34','href','#').
property('id34','id','id34').
parent('id30','id35').
property('id35','tag','li').
property('id35','id','id35').
parent('id35','id36').
property('id36','tag','a').
property('id36','href','#').
property('id36','id','id36').
parent('navbar','id37').
property('id37','tag','form').
property('id37','class','navbar-form navbar-right').
property('id37','role','search').
property('id37','id','id37').
parent('id37','id38').
property('id38','tag','div').
property('id38','class','form-group').
property('id38','id','id38').
parent('id38','id39').
property('id39','tag','input').
property('id39','type','text').
property('id39','class','form-control').
property('id39','id','id39').
parent('id37','id40').
property('id40','tag','button').
property('id40','type','submit').
property('id40','class','btn btn-default').
property('id40','id','id40').
parent('id9','id41').
property('id41','tag','div').
property('id41','class','jumbotron feature').
property('id41','id','id41').
parent('id41','id42').
property('id42','tag','div').
property('id42','class','container').
property('id42','id','id42').
parent('id42','id43').
property('id43','tag','h1').
property('id43','id','id43').
parent('id43','id44').
property('id44','tag','span').
property('id44','class','glyphicon glyphicon-equalizer').
property('id44','id','id44').
parent('id42','id45').
property('id45','tag','p').
property('id45','id','id45').
parent('id42','id46').
property('id46','tag','p').
property('id46','id','id46').
parent('id46','id47').
property('id47','tag','a').
property('id47','class','btn btn-default').
property('id47','href','#').
property('id47','id','id47').
parent('id9','id48').
property('id48','tag','div').
property('id48','class','container').
property('id48','id','id48').
parent('id48','id49').
property('id49','tag','div').
property('id49','class','row').
property('id49','id','id49').
parent('id49','id50').
property('id50','tag','div').
property('id50','class','col-lg-12').
property('id50','id','id50').
parent('id50','id51').
property('id51','tag','h1').
property('id51','class','page-header').
property('id51','id','id51').
parent('id51','id52').
property('id52','tag','small').
property('id52','id','id52').
parent('id50','id53').
property('id53','tag','p').
property('id53','id','id53').
parent('id48','id54').
property('id54','tag','div').
property('id54','class','row').
property('id54','id','id54').
parent('id54','id55').
property('id55','tag','article').
property('id55','class','col-md-4 article-intro').
property('id55','id','id55').
parent('id55','id56').
property('id56','tag','a').
property('id56','href','#').
property('id56','id','id56').
parent('id56','id57').
property('id57','tag','img').
property('id57','class','img-responsive img-rounded').
property('id57','src','holder.js/700x300').
property('id57','alt','').
property('id57','id','id57').
parent('id55','id58').
property('id58','tag','h3').
property('id58','id','id58').
parent('id58','id59').
property('id59','tag','a').
property('id59','href','#').
property('id59','id','id59').
parent('id55','id60').
property('id60','tag','p').
property('id60','id','id60').
parent('id54','id61').
property('id61','tag','article').
property('id61','class','col-md-4 article-intro').
property('id61','id','id61').
parent('id61','id62').
property('id62','tag','a').
property('id62','href','#').
property('id62','id','id62').
parent('id62','id63').
property('id63','tag','img').
property('id63','class','img-responsive img-rounded').
property('id63','src','holder.js/700x300').
property('id63','alt','').
property('id63','id','id63').
parent('id61','id64').
property('id64','tag','h3').
property('id64','id','id64').
parent('id64','id65').
property('id65','tag','a').
property('id65','href','#').
property('id65','id','id65').
parent('id61','id66').
property('id66','tag','p').
property('id66','id','id66').
parent('id54','id67').
property('id67','tag','article').
property('id67','class','col-md-4 article-intro').
property('id67','id','id67').
parent('id67','id68').
property('id68','tag','a').
property('id68','href','#').
property('id68','id','id68').
parent('id68','id69').
property('id69','tag','img').
property('id69','class','img-responsive img-rounded').
property('id69','src','holder.js/700x300').
property('id69','alt','').
property('id69','id','id69').
parent('id67','id70').
property('id70','tag','h3').
property('id70','id','id70').
parent('id70','id71').
property('id71','tag','a').
property('id71','href','#').
property('id71','id','id71').
parent('id67','id72').
property('id72','tag','p').
property('id72','id','id72').
parent('id9','id73').
property('id73','tag','footer').
property('id73','id','id73').
parent('id73','id74').
property('id74','tag','div').
property('id74','class','footer-blurb').
property('id74','id','id74').
parent('id74','id75').
property('id75','tag','div').
property('id75','class','container').
property('id75','id','id75').
parent('id75','id76').
property('id76','tag','div').
property('id76','class','row').
property('id76','id','id76').
parent('id76','id77').
property('id77','tag','div').
property('id77','class','col-sm-4 footer-blurb-item').
property('id77','id','id77').
parent('id77','id78').
property('id78','tag','h3').
property('id78','id','id78').
parent('id78','id79').
property('id79','tag','span').
property('id79','class','glyphicon glyphicon-fire').
property('id79','id','id79').
parent('id77','id80').
property('id80','tag','p').
property('id80','id','id80').
parent('id77','id81').
property('id81','tag','p').
property('id81','id','id81').
parent('id81','id82').
property('id82','tag','a').
property('id82','class','btn btn-default').
property('id82','href','#').
property('id82','id','id82').
parent('id76','id83').
property('id83','tag','div').
property('id83','class','col-sm-4 footer-blurb-item').
property('id83','id','id83').
parent('id83','id84').
property('id84','tag','h3').
property('id84','id','id84').
parent('id84','id85').
property('id85','tag','span').
property('id85','class','glyphicon glyphicon-cloud-upload').
property('id85','id','id85').
parent('id83','id86').
property('id86','tag','p').
property('id86','id','id86').
parent('id83','id87').
property('id87','tag','p').
property('id87','id','id87').
parent('id87','id88').
property('id88','tag','a').
property('id88','class','btn btn-default').
property('id88','href','#').
property('id88','id','id88').
parent('id76','id89').
property('id89','tag','div').
property('id89','class','col-sm-4 footer-blurb-item').
property('id89','id','id89').
parent('id89','id90').
property('id90','tag','h3').
property('id90','id','id90').
parent('id90','id91').
property('id91','tag','span').
property('id91','class','glyphicon glyphicon-leaf').
property('id91','id','id91').
parent('id89','id92').
property('id92','tag','p').
property('id92','id','id92').
parent('id89','id93').
property('id93','tag','p').
property('id93','id','id93').
parent('id93','id94').
property('id94','tag','a').
property('id94','class','btn btn-default').
property('id94','href','#').
property('id94','id','id94').
parent('id73','id95').
property('id95','tag','div').
property('id95','class','small-print').
property('id95','id','id95').
parent('id95','id96').
property('id96','tag','div').
property('id96','class','container').
property('id96','id','id96').
parent('id96','id97').
property('id97','tag','p').
property('id97','id','id97').
parent('id97','id98').
property('id98','tag','a').
property('id98','href','#').
property('id98','id','id98').
parent('id97','id99').
property('id99','tag','a').
property('id99','href','#').
property('id99','id','id99').
parent('id97','id100').
property('id100','tag','a').
property('id100','href','#').
property('id100','id','id100').
parent('id96','id101').
property('id101','tag','p').
property('id101','id','id101').
